### ISSUE TITLE
Miles font too small for certain miles in pane

### ISSUE THREAD

**Issue by bridgetglewis** [AlaskaAirlines/auro-pane#38]
## Verify the version of @alaskaairux/auro-pane you have installed

**The current version is:**
[![See it on NPM!](https://img.shields.io/npm/v/@alaskaairux/auro-pane?style=for-the-badge&color=orange)](https://www.npmjs.com/package/@alaskaairux/auro-pane)

My project has @alaskaairux/auro-pane v installed

## To Reproduce

1. Go to '[...](https://www.alaskaair.com/search/)' and search for a one-way with miles from SEA to LAX on 11/22/2023
2. On the results page, you should see shoulder dates with multiple miles options (i.e. 7k, 12.5k)
3. The font size for the different miles options are different.

Are you able to reproduce this issue on the [Auro doc site](https://auro.alaskaair.com/)?

- [ ] YES
- [x] NO

## Desktop (please complete the following information):

 - OS: MacOS
 - Browser: Chrome

**Comment by shonore-aa** [comment]
When shopping using miles, the text size for the mileage price within the shoulder dates varies depending on how many digits there are or if a decimal appears. We should use a consistent text size for all should date pricing.

Screen Shot 2023-03-29 at 11.26.31 AM.png 
Expected Behavior: Text sizes are the same regardless of the number of digits or if there is a decimal in the miles price. Should be using var(--auro-text-body-size-sm).

**Comment by blackfalcon** [comment]
Some comments here about how this area of the element works. See in the screen shot below that there is a default price size and when the character limit exceeds `6`, the smaller type size is applied. 

<img width="701" alt="Screen Shot 2023-06-12 at 10 45 19 AM" src="https://github.com/AlaskaAirlines/auro-pane/assets/181089/cec30c5b-f57c-4de4-886e-c9c7c30fad77">

The update @shonore-aa submitted with the PR changes this behavior. So that would make this a BREAKING change and I do not care for a BREAKING CHANGE for a feature like this. 

<img width="695" alt="Screen Shot 2023-06-12 at 10 49 48 AM" src="https://github.com/AlaskaAirlines/auro-pane/assets/181089/f717f3c2-b932-470f-8d0b-8c2d8126d48e">

This update does not impact the mobile versions of the element. 

The following statement of `The font size for the different miles options are different.` is true because of this pre-defined behavior. 

None of the demos we have on the docsite show examples of using miles versus $$ values. I feel we have a changing use case. 

IMHO, this character limit solution set a trap for us. I'd prefer a solution update that is more declarative and deprecate this character solution if it's not being used. 

E.g., what I see here is a misuse of the `price` attribute 

```
price="12.5k +"
```

We should have a `price` and a `miles` attribute.

**Comment by shonore-aa** [comment]
> Some comments here about how this area of the element works. See in the screen shot below that there is a default price size and when the character limit exceeds `6`, the smaller type size is applied.
> 
> <img alt="Screen Shot 2023-06-12 at 10 45 19 AM" width="701" src="https://user-images.githubusercontent.com/181089/245225363-cec30c5b-f57c-4de4-886e-c9c7c30fad77.png">
> The update @shonore-aa submitted with the PR changes this behavior. So that would make this a BREAKING change and I do not care for a BREAKING CHANGE for a feature like this.
> 
> <img alt="Screen Shot 2023-06-12 at 10 49 48 AM" width="695" src="https://user-images.githubusercontent.com/181089/245226011-f717f3c2-b932-470f-8d0b-8c2d8126d48e.png">
> This update does not impact the mobile versions of the element.
> 
> The following statement of `The font size for the different miles options are different.` is true because of this pre-defined behavior.
> 
> None of the demos we have on the docsite show examples of using miles versus $$ values. I feel we have a changing use case.
> 
> IMHO, this character limit solution set a trap for us. I'd prefer a solution update that is more declarative and deprecate this character solution if it's not being used.
> 
> E.g., what I see here is a misuse of the `price` attribute
> 
> ```
> price="12.5k +"
> ```
> 
> We should have a `price` and a `miles` attribute.

@blackfalcon  Thank you for the feedback and for sharing your opinion. I am not quite following your logic on why its a "BREAKING CHANGE" to be honest. I think this solution is fine for accomplishing the scope of the ticket. I do not want to over-engineer the solution.

**Comment by shonore-aa** [comment]
> > Some comments here about how this area of the element works. See in the screen shot below that there is a default price size and when the character limit exceeds `6`, the smaller type size is applied.
> > <img alt="Screen Shot 2023-06-12 at 10 45 19 AM" width="701" src="https://user-images.githubusercontent.com/181089/245225363-cec30c5b-f57c-4de4-886e-c9c7c30fad77.png">
> > The update @shonore-aa submitted with the PR changes this behavior. So that would make this a BREAKING change and I do not care for a BREAKING CHANGE for a feature like this.
> > <img alt="Screen Shot 2023-06-12 at 10 49 48 AM" width="695" src="https://user-images.githubusercontent.com/181089/245226011-f717f3c2-b932-470f-8d0b-8c2d8126d48e.png">
> > This update does not impact the mobile versions of the element.
> > The following statement of `The font size for the different miles options are different.` is true because of this pre-defined behavior.
> > None of the demos we have on the docsite show examples of using miles versus $$ values. I feel we have a changing use case.
> > IMHO, this character limit solution set a trap for us. I'd prefer a solution update that is more declarative and deprecate this character solution if it's not being used.
> > E.g., what I see here is a misuse of the `price` attribute
> > ```
> > price="12.5k +"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We should have a `price` and a `miles` attribute.
> 
> @blackfalcon Thank you for the feedback and for sharing your opinion. I am not quite following your logic on why its a "BREAKING CHANGE" to be honest. I think this solution is fine for accomplishing the scope of the issue. I do not want to over-engineer the solution.

@blackfalcon The definition of a "BREAKING CHANGE" in software development is "A modification or update made to a software system that is not backward compatible with previous versions. ". I am simply updating logic for a cosmetic CSS change. The solution is backwards compatible and does not potentially causes other components to fail.

**Comment by blackfalcon** [comment]
@shonore-aa please keep in mind that these are UI components and any change in the UI has a ripple effect across any number of consumers of this UI element. When working in the scope of a design system, the term "... simply updating logic for a cosmetic CSS" is not appropriate.

**Comment by blackfalcon** [comment]
The last discussed solution was to build a function within the scope of the element that is aware of the max width available for content and the size of the string being inserted. Once the string exceeds the max width, the element would apply a CSS selector that would reduce the size of the font. 

This addresses all concerns of the issue. 

1. This does not 'change' the expected outcome of the current feature that is hard-coded as `6` characters 
2. This does not add new APIs to the scope of the element that will cause additional work on consumers 

This work can be completed as a `perf` update as this is NOT a fix to a bug nor a new feature.
